# Generated by Django 3.1.3 on 2020-12-01 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Impressora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='Endereço IP')),
                ('nome', models.CharField(choices=[(1, 'BROTHER DCP6250DW')], max_length=50, verbose_name='Nome')),
                ('nivel_toner', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Nível Toner')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Departamento', to='crawler.departamento')),
            ],
        ),
    ]
